repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check
        language: system
        types: [python]

      - id: ruff-format
        name: ruff-format
        entry: ruff format
        language: system
        types: [python]

      - id: frontend-lint
        name: frontend lint
        entry: bash -c "cd browser-extension && npm run lint"
        language: system
        pass_filenames: false

      - id: frontend-format
        name: frontend format
        entry: bash -c "cd browser-extension && npm run format"
        language: system
        pass_filenames: false

      - id: frontend-build
        name: frontend build
        entry: bash -c "cd browser-extension && npm run build"
        language: system
        pass_filenames: false

  - repo: https://github.com/PyCQA/bandit
    rev: 1.9.2
    hooks:
      - id: bandit
        args: ["-r", "./app"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: ^dataset/
