services:
  - type: web
    name: email-spam-detector
    env: python
    branch: develop
    buildCommand: pip install -r requirements.txt
    startCommand: python -m app.py --debug --port $PORT
    plan: free